### PR TITLE
Allow using a function to set cache-control headers

### LINKED ISSUE #94: allow different cache times for different urls
From nodeapps/http-server#63:

> Currently http-server allows you to configure the "cache-control: max-age" value for all urls. But often you want a short max-age for e.g. /{index.html} and a long max-age for urls to versioned assets like /styles/f35ac111.main.css.
>
> Would you accept a patch to allow specifying different max-ages for different urls?

I realized http-server is just using ecstatic under the hood, which also only allows setting a single max-age for all responses.

Any suggestions on the simplest approach to giving versioned assets a longer max-age than non-versioned assets? Would be happy to submit a patch if there is interest in supporting this.

### PR DESCRIPTION
**Pull request by TehShrike**
Fixes #94

I didn't see any tests involving cache-control or I would have added to them.

### CODE REVIEW

**Comment by jfhbrook** [comment]
It's a gap in the test coverage.

**Comment by TehShrike** [comment]
If it works, are you willing to merge this without more tests, or do you want to see some tests for cache headers first?

**Comment by TehShrike** [comment]
Let me know if I can do anything to make this more mergable.

**Comment by jfhbrook** [comment]
Hey, sorry.

Current status: I've been trying to decide if I'm gonna write tests for this or not.

**Comment by TehShrike** [comment]
No worries! Let me know what you decide.  If I get a chance before you make your move, I may try my hand at it myself.

**Comment by TehShrike** [comment]
I pushed up some tests for the cache option, let me know how you feel about them!

**Comment by jfhbrook** [comment]
Published as 1.2.0

Sorry for the long wait!

**Comment by TehShrike** [comment]
w00t!

**Pull request merged**
