### PR TITLE
Backport vuln fix to major version 3

### PR DESCRIPTION
**Pull request by Blackbaud-ShaydeNofziger**
Cherry-picked the patch commit that resolved the [Open Redirect vulnerability](https://www.npmjs.com/advisories/830) announced.

### CODE REVIEW

**Comment by Blackbaud-ShaydeNofziger** [comment]
Obviously can't merge to master - we'd need a different target branch to release this through.

**Comment by thornjad** [comment]
@jfhbrook could make a `v3` branch or something like that

**Comment by Blackbaud-ShaydeNofziger** [comment]
@jfhbrook when you are able, could you please make a new branch, `v3` or similar based off of the b1ad80189fcd7f2410efbc9347361fe69d165de8 3.3.1 release commit?

**Comment by chase-moskal** [comment]
instead of waiting around, i suppose there's no harm in anybody temporarily publishing `ecstatic-fix-830@3.0.1-fixed.1` or something like that, straight from this branch, if distributing the fix rapidly was desirable

**Comment by jfhbrook** [comment]
I can push this out tomorrow morning.

**Comment by jfhbrook** [comment]
Rather than trying to pull down this branch I just replayed your steps. The result is published as 3.3.2. Cheers!

**Comment by Blackbaud-ShaydeNofziger** [comment]
@jfhbrook Awesome, thanks bud!

**Pull request closed without merging**
