### PR TITLE
[test][fix] Set "Connection: close" header on malformed test request.

### LINKED ISSUE #170: Test "malformed" fails with timeout
I cloned 7bf3f08 , ran `npm i; npm test`, it failed, and I have no idea why. I [added more logging](https://github.com/mk-pmb/node-ecstatic/commit/3732e899dcaad85eb02e8497e0cdb0edff2e8908) in an attempt to fix it, but to me the stderr messages look like the test should have succeeded. 
```text
$ npm test

> ecstatic@0.4.2 test /…/ecstatic
> tap test/*.js

ok test/304.js .......................................... 3/3
ok test/core.js ....................................... 27/27
ok test/express.js .................................... 37/37
not ok test/malformed.js ................................ 1/2
    Command: "node" "malformed.js"
    TAP version 13
    ok 1 should be equal
    not ok 2 test/malformed.js
      ---
        exit:     143
        timedOut: true
        stderr:   |
          listening on  { address: '0.0.0.0', family: 'IPv4', port: 43784 }
          status  400
          closing
        command:  "node" "malformed.js"
      ...
    
    1..2
    # tests 2
    # pass  1
    # fail  1
    
ok test/union.js ...................................... 27/27
total ................................................. 95/96

not ok
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

$ npm show ecstatic version
1.3.1

$ npm show tap version
2.3.1

$ nodejs --version
v0.10.40

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise
```

### PR DESCRIPTION
**Pull request by mk-pmb**
Fixes #170, a test timeout due to dangling listeners.

### CODE REVIEW

**Comment by mk-pmb** [comment]
No idea why github doesn't pick up my edit conflict resolution. I'll retry the PR.

**Comment by mk-pmb** [comment]
2nd attempt (redone from scratch) doesn't seem to avoid the merge conflict either. I hope you can still merge it somehow.

**Comment by dotnetCarpenter** [comment]
@jfhbrook  can not merge in a pull request that is not based of the master branch. You need to pull from the master branch and then create a branch from that, before you make your changes.

**Comment by mk-pmb** [comment]
I just hope his git is as capable as mine:
```text
$ git merge github/test-timeout-fix-170
Updating 7bf3f08..207e9fc
Fast-forward
 test/malformed.js |    1 +
```
… and it's just GitHub that doesn't see a way to fast-forward. If it really cannot be merged, the patch should be easy enough to add manually.

**Pull request closed without merging**
