### PR TITLE
Fix icon styles in showdir when text is wrapping in multiple lines

### PR DESCRIPTION
**Pull request by mahdi-ninja**
Before fix:
Before fix

After fix:
After fix

### CODE REVIEW

**Comment by jfhbrook** [comment]
This looks nice.

Can you do me a solid and update the changelog and contributors list before I merge?

**Comment by jfhbrook** [comment]
You unfortunately (well, fortunately moving forward, but for the purposes of this pr...) reminded me to merge a "we use modified airbnb now" PR, so there will have to be some manual work to make this merge cleanly.

If you can make it work, great, but if not, I can do the work, so don't stress too hard about the grey stuff if you can't fix it.

**Comment by mahdi-ninja** [comment]
I rebased my changes on master and updated changelog and contributors list.

**Comment by jfhbrook** [comment]
Thanks!

**Pull request merged**
