### PR TITLE
Remove charset=utf-8 default

### LINKED ISSUE #220: Wrong behavior of `application/wasm` mime type
Current webassebmly spec says
> Note: extra parameters are not allowed, including the empty `application/wasm;`.
https://webassembly.github.io/spec/web-api/index.html#streaming-modules

For now ecstatic adds charset in `Content-Type` for all filetypes, so mimetype for wasm files will be `application/wasm; charset=utf-8`. Can we somehow disable this for files with `application/wasm` mimetype (or for binary files at all?)?

I'll be happy to create PR if you tell me right way to figure out exclusions.

### PR DESCRIPTION
**Pull request by BigBlueHat**
Fixes #220 

This also fixes image loading issues when using `fetch()` + `createImageBitmap()` in Firefox:
https://github.com/indexzero/http-server/issues/296#issuecomment-338352458

### CODE REVIEW

**Comment by jfhbrook** [comment]
Thanks for trying to make ecstatic better! I agree that it's alarming that images break because of this. A few minor concerns:

1. This would be a major version bump as-is, which is fine in and of itself but I dunno that I'd consider this a patchfix of the main line. If this was feature flagged somehow (or made configurable s.t. you can set your own charsets) I could justify it being a minor, and then flip the defaults for a major later.
2. You mentioned being interested in upgrading the mime package--would that fix this "better"?

**Comment by BigBlueHat** [comment]
> made configurable s.t. you can set your own charsets

I wouldn't want to encourage a blanket `charset` setting option as that puts us back right where we are (passing `charset` on all the things).

Maybe an `--auto-charset` option would do the trick? It could become the default in a future major version and the defaulting to `utf-8` would be gone.

> You mentioned being interested in upgrading the mime package--would that fix this "better"?

See https://github.com/jfhbrook/node-ecstatic/issues/220#issuecomment-398443210 :)

**Comment by athei** [comment]
I also stumbled on this because it prevents Firefox from using wasm streaming instantiation. Why is this a major version bump? We are not breaking the API. It is a bug fix isn't it?

**Comment by jfhbrook** [comment]
One person's bugfix is another's expected behavior 🤷‍♂️

**Comment by athei** [comment]
Okay :D 

So the progress on this is stalling because you need to evaluate if you skip this patch alltogether and just apply #218 instead?

**Comment by jfhbrook** [comment]
I'm not merging #218, at least not as-is, it's open for discussion and so that someone can take the opportunity to fix the issues outlined in that PR.

FWIW I /believe/ this ticket is still an issue even with something along the lines of #218 merged.

**Comment by jfhbrook** [comment]
Dredged up https://github.com/jfhbrook/node-ecstatic/issues/44 which was the original issue--I think there are good reasons to specify the charset, hence why this exists in the first place.

**Comment by athei** [comment]
Yes and this patch delegates that charset decision to the mime library like it should. The charset should still be added to types that need it after that patch.

**Comment by jfhbrook** [comment]
A test that confirms that would be nice!

**Comment by jfhbrook** [comment]
Anyway, just to reiterate what I'm looking for around this and #44:

* Some answer to cases where setting charset would be appropriate--either delegating to an autodetect library, or an optional way to override, with tests
* Some answer to passing in custom types--either a separate library for parsing types files with new mime, or the ability to pass in a custom mimetypes resolver in javascript

**Comment by jfhbrook** [comment]
I get that you're frustrated, btw, with this long-standing issue that prevents a lot of cool things from working right. The problem is that I don't want to merge casual code, but don't have the time to implement the right thing myself. All I can say is, be the change you wish to see in the world.

**Comment by jfhbrook** [comment]
I rolled these changes into #240, which addresses the concerns I had by exposing a way to set a custom content-type lookup function. Thanks!

**Pull request closed without merging**
