### PR TITLE
fix: on-finished

### PR DESCRIPTION
**Pull request by ronag**
Use on-finished. `close` is not always emitted in every scenario in some "older" versions of node. I don't remember the exact specifics.

### CODE REVIEW

**Comment by ronag** [comment]
An alternative which is also (as compatible as I can think of is)

```js
function onFinished(req, res, cb) {
      req
        .on('close', cb)
        .on('aborted', cb)
        .on('error', cb)
      res
        .on('close', cb)
        .on('finish', cb)
        .on('error', cb)
}
```

**Comment by jfhbrook** [comment]
I have no problem bringing in a new dependency, this project has not very many as it is.

If I were to merge this, which PRs would this be an alternative to? It looks like this handles a case that #250 doesn't.

**Comment by ronag** [comment]
This is ready for merge.

**Comment by jfhbrook** [comment]
Released as 4.0.2. Thanks!

**Pull request merged**
